include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_code: error
    unused_import: error
    unused_local_variable: error
    unused_element: warning

    invalid_assignment: error
    return_of_invalid_type: error

    missing_required_param: error
    missing_return: error
    deprecated_member_use: warning

  exclude:
    - "**/*.g.dart"      
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_print: true             
    avoid_empty_else: true
    avoid_redundant_argument_values: true

    avoid_unused_constructor_parameters: true
    cancel_subscriptions: true
    close_sinks: true

    use_key_in_widget_constructors: true
    sized_box_for_whitespace: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    avoid_function_literals_in_foreach_calls: true
    prefer_expression_function_bodies: false  

    avoid_init_to_null: true
    unnecessary_null_checks: true
    prefer_null_aware_operators: true