name: direto_da_roca
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: 3.41.9

dependencies:
  flutter:
    sdk: flutter
  iod: ^0.0.3
  horta_ui:
    path: core_sdk/horta_ui
  common_models:
    path: core_sdk/common_models
  aiuri_sdk: 
    git:
      url: https://github.com/yohantsn/aiuri_sdk
      ref: 0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
